# other Jekyll Themes for GitHub Pages
# theme: jekyll-theme-minimal
# theme: jekyll-theme-architect
# theme: jekyll-theme-hacker
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-merlot
# theme: jekyll-theme-midnight
# theme: jekyll-theme-modernist
# theme: jekyll-theme-slate
# theme: jekyll-theme-tactile
# theme: jekyll-theme-time-machine

theme: jekyll-theme-cayman
include:
  - _layouts
  - assets
